### PR TITLE
don't replace PROTOC if already provided

### PR DESCRIPTION
**Pull request by Princemachiavelli**
Allow build environment to provide it's own `protoc`.

### CODE REVIEW

**Review by lukipuki — APPROVED** [review]

**Comment by Princemachiavelli** [comment]
Can someone with write access merge this PR? Thanks.

**Comment by lukipuki** [comment]
I think that's @ajmcquilkin

**Comment by Princemachiavelli** [comment]
@ajmcquilkin Any chance you can merge this?

**Review by ajmcquilkin — APPROVED** [review]

**Comment by ajmcquilkin** [comment]
Apologies for the delay! Thanks for the contribution :)

**Pull request merged**
